### ISSUE TITLE
Pics broken on Tinderesque Swipe

### ISSUE THREAD

**Issue by IanLeatherbury** [xamarin/customer-success#35]
Pics appear broken on [Tinderesque Swipe](https://github.com/xamarin/customer-success/tree/master/samples/Xamarin.iOS/TinderesqSwipe) sample. This is what I see:

![image](https://cloud.githubusercontent.com/assets/5083430/8417492/ea7bc626-1e61-11e5-9e7b-4ab3f1fa5c29.png)

**Comment by jon-davis-xamarin** [comment]
Resolved in #39
